// This file is generated by the Firebase CLI.
// Run: flutterfire configure
// Then replace this file with the generated firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// ⚠️  Replace with your actual values from Firebase Console > Project Settings
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // 🔴 REPLACE ALL VALUES BELOW with your Firebase project credentials
  // Get them from: Firebase Console → Project Settings → Your apps
  // ──────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEnBaEngQ9p8LkZNqtQ0phNJ2vdfYjVpo',
    appId: '1:732639221297:android:12302deb18315b50e36710',
    messagingSenderId: '732639221297',
    projectId: 'edathara-samskarika-samithi',
    storageBucket: 'edathara-samskarika-samithi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVxP8kKv1YILpes2ZgtxZW5ex0iv_YdQ',
    appId: '1:732639221297:ios:2379a7819bba0493e36710',
    messagingSenderId: '732639221297',
    projectId: 'edathara-samskarika-samithi',
    storageBucket: 'edathara-samskarika-samithi.firebasestorage.app',
    iosBundleId: 'com.loopz.edatharaSocialApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_08bEYnlGLKoqB2Efkh28k2lQLKlpvzs',
    appId: '1:732639221297:web:ccc88bef7be59746e36710',
    messagingSenderId: '732639221297',
    projectId: 'edathara-samskarika-samithi',
    authDomain: 'edathara-samskarika-samithi.firebaseapp.com',
    storageBucket: 'edathara-samskarika-samithi.firebasestorage.app',
    measurementId: 'G-HVE0B3H599',
  );

}