// This file is generated by the Firebase CLI.
// Run: flutterfire configure
// Then replace this file with the generated firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// ⚠️  Replace with your actual values from Firebase Console > Project Settings
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ──────────────────────────────────────────────────────────────────────────
  // 🔴 REPLACE ALL VALUES BELOW with your Firebase project credentials
  // Get them from: Firebase Console → Project Settings → Your apps
  // ──────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQR0MjA1A1WYzaefej8BMRZRrdhSBxryk',
    appId: '1:24971684992:android:c72b23e57294a04bbc0a65',
    messagingSenderId: '24971684992',
    projectId: 'slot-bookingapp',
    storageBucket: 'slot-bookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1eAzi6U6NzUnLTf2VKV-a9eWrBS8GxY',
    appId: '1:24971684992:ios:69b0df28985f25acbc0a65',
    messagingSenderId: '24971684992',
    projectId: 'slot-bookingapp',
    storageBucket: 'slot-bookingapp.firebasestorage.app',
    iosBundleId: 'com.loopz.edatharaSocialApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGUEbmv-6Gftk1hc1wF4RBQ7lGXggA5I',
    appId: '1:24971684992:web:b4c825255919431abc0a65',
    messagingSenderId: '24971684992',
    projectId: 'slot-bookingapp',
    authDomain: 'slot-bookingapp.firebaseapp.com',
    storageBucket: 'slot-bookingapp.firebasestorage.app',
    measurementId: 'G-C8BNLXWPWH',
  );

}